### ISSUE TITLE
Directory Omissions

### ISSUE THREAD

**Issue by brandonstephens922** [bryant-treacle/SSL_Traffic_Hunting#6]
When attempting to install this on the current version of Security Onion, the script is omitting these directories:

cp: omitting directory '/opt/bro/share/bro/ja3'
cp: omitting directory '/opt/bro/share/bro/policy/custom-scripts/ja3'
cp: omitting directory '/opt/bro/share/bro/ja3'
cp: omitting directory '/opt/bro/share/bro/policy/custom-scripts/ja3'

My assumption is that this was published before the ja3.bro script was added to the natice SO image. At this point, I am not getting the ja3_description field added to the ssl.log.

**Comment by bryant-treacle** [comment]
@brandonstephens922 

      I just ran a clean install of 16.04.6.2 running in standalone mode and it worked for me.  Are you installing it on a standalone/sensor?
The install script attempts to locate the directory where JA3 is installed on the sensor (default is /opt/bro/share/bro/ja3) by running (find /opt/ -type d -name "ja3" ) then copies the ja3.bro and ja3_lookup.dat files into that directory.  Those files are located in the files folder in the repo.  You can try to do that manually then restarting bro (so-bro-restart) and see if it works.  Let me know if it works.

Bryant

**Comment by brandonstephens922** [comment]
So I found the issue, it involved a previous custom-script on my end. I had been running the ja3.bo script prior to it being part of SO. I deleted the script from the custom-scripts directory, reran install.sh and everything came together nicely. Thanks for the quick support and nice presentation last week at SOC!
